### ISSUE TITLE
Solderless breadboard implementation?

### ISSUE THREAD

**Issue by BurtHarris** [alwynallan/redoubler#3]
I've got a couple of CY8CKIT-059 modules handy, is there any reason I shouldn't be able to breadboard the external resistors in order to try this out?

**Comment by alwynallan** [comment]
Solderless breadboards have unreliable connections and lots of stray pin
capacitance. With a $10 CY8KIT-059 I would solder the 8 resistors to it.
Here's how mine looks:

A. Peter Allan · 450 Timber Lane · Devon PA 19333 · 610-687-1708 ·
610-547-4836 mobile

**Comment by BurtHarris** [comment]
Sure, understood, even though the picture didn't come through.
